name: docgen
run-name: Build docs
on: [push]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Python Libraries
        run: python -m pip install --upgrade pip setuptools wheel markdown-it-py
      - name: Run Script
        run: python parsemd.py